Probabilities: # Probabilities of strands' lengths, will be normalized if they don't sum to 1. Integer > 1: positive real number
  2: 0.25
  3: 0.25
  4: 0.25
#Limits: at least one of them must be specified
MaxAddedStrands: 10 # Maximum number of new strands to add during each loop. Positive integer
#MaxLigationEvents: 10 # Maximum number of ligation events to perform during each loop. Positive integer
#NucleotidesToConsume: 10 # Number of nucleotides to consume for ligation. Positive integer